version: '3.7'

services:
  coaster:
    build:
      context: .
      target: development
    command: npm run dev
    ports:
      - '8088:8088'
    volumes:
      - .:/home/node/coaster
      - coaster_node_modules:/home/node/coaster/node_modules

volumes:
  coaster_node_modules:
