version: '3.7'

services:
  coaster:
    build:
      context: .
      target: development
    depends_on:
      - postgres
    command: npm run dev
    ports:
      - '8088:8088'
    volumes:
      - .:/home/node/coaster
      - coaster_node_modules:/home/node/coaster/node_modules

  postgres:
    image: postgres:12
    network_mode: "host"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}

volumes:
  coaster_node_modules:
