name: Linter and TypeScript compilation

on: [push, pull_request]
jobs:
  lint:
    name: Compile TypeScript and lint the code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: npm ci
        run: npm ci
      - name: lint tsc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tsc

          npm run lint
