name: Linter

on: push
jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
          with:
            node-version: '13.x'
        run: npm i
        run: npm run lint
