name: Test runner action

on: [push, pull_request]
jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: coaster
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: coasterdevelopment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: Build docker images
        run: docker-compose build

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
