name: Typescript compile checker

on: push
jobs:
  typescript-compile-checker:
    name: Run the TypeScript compiler to check for errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
          with:
            node-version: '13.x'
        run: npm i
        run: tsc
